plugins {
    id 'java'
}

group = 'ru.mail.flores01.lena'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.1'
    testImplementation 'com.codeborne:selenide:7.0.2'
}

test {
    useJUnitPlatform()
    systemProperty "file.encoding", "utf-8"
    systemProperty "selenide.fileEncoding", "utf-8"
}

tasks.withType(Test).configureEach {
    systemProperty "file.encoding", "UTF-8"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}